name: Testing

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install Dependencies"
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install .
    - name: Test with pytest
      run: |
        pytest --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
